../src/merge_sequential 500 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 1000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 2000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 4000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 8000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 16000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 32000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 64000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 128000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 256000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 512000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 1024000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 2048000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 4096000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 8192000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 16384000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 32768000 >> ../results/merge/merge_sequential_0.rs
../src/merge_sequential 65536000 >> ../results/merge/merge_sequential_0.rs
