mpirun -np 4 ../src/merge_parallel 500 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 1000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 2000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 4000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 8000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 16000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 32000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 64000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 128000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 256000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 512000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 1024000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 2048000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 4096000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 8192000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 16384000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 32768000 >> ../results/merge/merge_parallel_0.rs
mpirun -np 4 ../src/merge_parallel 65536000 >> ../results/merge/merge_parallel_0.rs
