../src/merge_sequential 500 >> ../results/merge_sequential_0.rs
../src/merge_sequential 500 >> ../results/merge_sequential_1.rs
../src/merge_sequential 500 >> ../results/merge_sequential_2.rs
../src/merge_sequential 500 >> ../results/merge_sequential_3.rs
../src/merge_sequential 500 >> ../results/merge_sequential_4.rs
../src/merge_sequential 500 >> ../results/merge_sequential_5.rs
../src/merge_sequential 500 >> ../results/merge_sequential_6.rs
../src/merge_sequential 500 >> ../results/merge_sequential_7.rs
../src/merge_sequential 500 >> ../results/merge_sequential_8.rs
../src/merge_sequential 500 >> ../results/merge_sequential_9.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 500 >> ../results/merge_sequential_0.rs
../src/merge_sequential 500 >> ../results/merge_sequential_1.rs
../src/merge_sequential 500 >> ../results/merge_sequential_2.rs
../src/merge_sequential 500 >> ../results/merge_sequential_3.rs
../src/merge_sequential 500 >> ../results/merge_sequential_4.rs
../src/merge_sequential 500 >> ../results/merge_sequential_5.rs
../src/merge_sequential 500 >> ../results/merge_sequential_6.rs
../src/merge_sequential 500 >> ../results/merge_sequential_7.rs
../src/merge_sequential 500 >> ../results/merge_sequential_8.rs
../src/merge_sequential 500 >> ../results/merge_sequential_9.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 1000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 2000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 5000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 10000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 15000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 30000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 50000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 75000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 100000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 250000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 350000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 500000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 750000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 1000000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 1500000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 2000000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 5000000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 7500000 >> ../results/merge_sequential_9.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_0.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_1.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_2.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_3.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_4.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_5.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_6.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_7.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_8.rs
../src/merge_sequential 10000000 >> ../results/merge_sequential_9.rs
